SRS_Game/Models/Document.cs
using SRS_Game.Data;
using SRS_Game.Models.Srs;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SRS_Game.Models
{
    public class Document
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// Nazwa dokumentu
        /// </summary>
        [Required(ErrorMessage = "The field is required")]
        public string Name { get; set; }

        /// <summary>
        /// Przeznaczenie
        /// </summary>
        public string? Destination { get; set; }

        [Required(ErrorMessage = "The field is required")]
        [DisplayName("Author")]
        [ForeignKey(nameof(Participant))]
        public int AuthorId { get; set; }

        /// <summary>
        /// Nr zespołu
        /// </summary>
        [ForeignKey(nameof(Team))]
        public int? TeamId { get; set; }

        [DisplayName("Team Leader")]
        [Required(ErrorMessage = "The field is required")]
        [ForeignKey(nameof(Participant))]
        public int TeamLeaderId { get; set; }

        [DisplayName("Project")]
        [ForeignKey(nameof(Project))]
        public int? ProjectId { get; set; }

        [DisplayName("Created date")]
        public DateTime CreatedDate { get; set; }

        [Required(ErrorMessage = "The field is required")]
        [DisplayName("Updated date")]
        public DateTime UpdatedDate { get; set; } = DateTime.Now;

        /// <summary>
        /// Wersja dokumentu
        /// </summary>
        [Required(ErrorMessage = "The field is required")]
        [DisplayName("Version")]
        public int Version { get; set; }

        /// <summary>
        /// Percent 0% - 100%
        /// </summary>
        public int? Rate {  get; set; }

        public Document() { }

        public Document(string name, string? destinatiption, int authorId, int? team, int teamLeaderId, int? projectId, 
            DateTime createDate, DateTime updateDate, int versionId, int? rate = 0)
        {
            Name = name;
            Destination = destinatiption;
            AuthorId = authorId;
            TeamId = team;
            TeamLeaderId = teamLeaderId;
            ProjectId = projectId;
            CreatedDate = createDate;
            UpdatedDate = updateDate;
            Version = versionId;
            Rate = rate;
        }
    }

    public class DocumentViewModel : Document
    {
        public string Project { get; set; } = string.Empty;
        public string Author { get; set; } = string.Empty;
        public string Team { get; set; } = string.Empty;
        public string Owner { get; set; } = string.Empty;
        public string XamlContent { get; set; } = string.Empty;
        public IEnumerable<Attachement> Attachements { get; set; } = Enumerable.Empty<Attachement>();
        public IEnumerable<DocumentHistoryViewModel> History { get; set; } = Enumerable.Empty<DocumentHistoryViewModel>();
    }

    public class DocumentEditViewModel : DocumentViewModel
    {
        public SRS? SRS { get; set; }
    }

    public class DocumentStakeholderRel
    {
        [ForeignKey(nameof(Document))]
        public required int DocumentId { get; set; }

        [ForeignKey(nameof(Participant))]
        public required int StakeholderId { get; set; }
    }
}

SRS_Game/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography.Xml;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Xml.Linq;
using System.Xml.Serialization;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using SRS_Game.Data;
using SRS_Game.Helpers;
using SRS_Game.Interfaces;
using SRS_Game.Models;
using SRS_Game.Models.Srs;

namespace SRS_Game.Controllers
{
    //[Authorize(Roles = "Owner,User")]
    public class DocumentsController : Controller
    {
        private readonly SRS_GameDbContext _context;
        private readonly IReadableParticipant _readableParticipant;
        private readonly IReadableProject _readableProject;
        private readonly IReadableTeam _readableTeam;
        private readonly IReadableAttachement _readableAttachement;
        private readonly IReadableDocument _readableDocument;
        private readonly IWritableDocument _writableDocument;
        private readonly IStringLocalizer<DocumentsController> _localizer;

        public DocumentsController(SRS_GameDbContext context
            , IReadableParticipant readableParticipant
            , IReadableProject readableProject
            , IReadableTeam readableTeam
            , IReadableAttachement readableAttachement
            , IReadableDocument readableDocument
            , IWritableDocument writableDocument, IStringLocalizer<DocumentsController> localizer)
        {
            _context = context;
            _readableParticipant = readableParticipant;
            _readableProject = readableProject;
            _readableTeam = readableTeam;
            _readableAttachement = readableAttachement;
            _readableDocument = readableDocument;
            _writableDocument = writableDocument;
            _localizer = localizer;
        }

        // GET: Documents
        public async Task<IActionResult> Index()
        {
            var documents = await (from document in _context.Documents
                        join author in _context.Participants
                        on document.AuthorId equals author.Id
                        join project in _context.Projects
                        on document.ProjectId equals project.Id
                        select new DocumentViewModel
                        {
                            Id = document.Id,
                            Name = document.Name,
                            Project = project.Name,
                            Version = document.Version,
                            UpdatedDate = document.UpdatedDate,
                            Author = author.GetParticipantName()
                        }).ToListAsync();

            if (documents == null || documents.Count == 0)
            { 
                return NotFound();
            }

            return View(documents);
        }

        // GET: Documents/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var document = await _readableDocument.GetAsync(id);

            if (document == null)
            {
                return NotFound();
            }

            document.Attachements = _readableAttachement.GetAllForDocument(id);
            document.History = _readableDocument.GetDocumentHistories(id);

            var spec = _readableDocument.GetSpecification(id, document.Version);
            if (spec != null)
            {
                string xamlContent = spec.XamlContent;
                document.XamlContent = xamlContent;
            }

            return View(document);
        }

        // GET: Documents/Create
        [Authorize(Policy = "AdminOrOwnerPolicy")]
        public async Task<IActionResult> Create()
        {
            ViewBag.Participants = await _readableParticipant.GetParticipantsForSelectListAsync();
            ViewBag.Projects = await _readableProject.GetProjectsForSelectListAsync();

            return View();
        }

        // POST: Documents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Policy = "AdminOrOwnerPolicy")]
        public async Task<IActionResult> Create(Models.Document document)
        {
            if (ModelState.IsValid)
            {
                document.CreatedDate = DateTime.Now;
                _context.Add(document);
                await _context.SaveChangesAsync();
                
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Message = new Alert { Type = AlertType.danger, Text = "Model state is not valid." };

            ViewBag.Participants = await _readableParticipant.GetParticipantsForSelectListAsync();
            ViewBag.Projects = await _readableProject.GetProjectsForSelectListAsync();

            return View(document);
        }

        // GET: Documents/Edit/5
        [Authorize(Policy = "AdminOrOwnerPolicy")]
        public async Task<IActionResult> Edit(int id)
        {
            //var document = await _context.Documents.FindAsync(id);

            var document = await _readableDocument.GetAsync(id);
            
            if (document == null)
            {
                return NotFound();
            }

            var stakholderTypes = Enum.GetValues(typeof(StakeholderType))
                .Cast<StakeholderType>()
                .Select(x => new SelectListItem { Text = x.ToString(), Value = ((int)x).ToString() })
                .ToList();
            
            //stakholderTypes.Insert(0, new SelectListItem { Value = "-1", Text = "-- Select an option --" });

            var priorities = Enum.GetValues(typeof(Priority))
                .Cast<Priority>()
                .Select(x => new SelectListItem { Text = _localizer[x.ToString()], Value = ((int)x).ToString() })
                .ToList();

            //priorities.Insert(0, new SelectListItem { Value = "-1", Text = "-- Select an option --" });

            var participants = await _readableParticipant.GetParticipantsForSelectListAsync();
            var projects = await _readableProject.GetProjectsForSelectListAsync();
            var teams = await _readableTeam.GetTeamsForSelectListAsync();

            ViewBag.Priorities = priorities;
            ViewBag.StakeholderTypes = stakholderTypes;
            ViewBag.Projects = projects;
            ViewBag.Teams = teams;

            var transcriptFileId = await _readableDocument.GetAttachements(id, transcriptsOnly: true);

            if (transcriptFileId != null && transcriptFileId.Count != 0)
            {
                var fileContent = await _readableAttachement.GetContentAsync(transcriptFileId[0]);
                if (fileContent != null)
                {
                    var meetingTranscript = new TranscriptParser(fileContent);

                    ViewData["TopicS"] = meetingTranscript.Topic;
                    ViewData["MeetingDateS"] = meetingTranscript.MeetingDate;
                    ViewData["ParticipantsS"] = MyRegex.NewLineToBr(meetingTranscript.Participants);
                    ViewData["ContentS"] = MyRegex.NewLineToBr(meetingTranscript.MeetingContent);
                }
            }

            SRS? srsDoc = null;
            var spec = _readableDocument.GetSpecification(id, document.Version);
            
            if (spec != null)
            {
                string xamlContent = spec.XamlContent;
                srsDoc = XamlSerializer.DeserializeObjectToXaml(xamlContent);
                //srsDoc.Attachements = _readableAttachement.GetAllForDocument(id).ToList();
                srsDoc.Attachements = [.. _context.Attachements
                    .Where(a => a.DocumentId == id)
                    .OrderBy(a => a.FileName)
                    .Select(a => new SrsAttachement
                    {
                        FileName = a.FileName,
                        ContentType = a.ContentType,
                        CreatedDate = a.CreatedDate
                    })];
            }
            else
            {
                srsDoc = new SRS
                {
                    ProjectName = document.Project ?? "",
                    TeamNumber = document.Team ?? "",
                    Version = document.Version,
                    Author = document.Author,
                    Owner = document.Owner ?? "",
                    CreatedDate = document.CreatedDate,
                    UpdatedDate = document.UpdatedDate,
                };
            }

            var viewModel = new DocumentEditViewModel
            {
                Id = document.Id,
                Name = document.Name,
                Destination = document.Destination,
                ProjectId = document.ProjectId,
                AuthorId = document.AuthorId,
                Author = document.Author,
                Owner = document.Owner,
                Version = document.Version,
                CreatedDate = document.CreatedDate.ToLocalTime(),
                UpdatedDate = document.UpdatedDate.ToLocalTime(),
                TeamId = document.TeamId,
                TeamLeaderId = document.TeamLeaderId,
                History = _readableDocument.GetDocumentHistories(id),
                SRS = srsDoc
            };

            ViewBag.Participants = participants;
            ViewBag.History = _readableDocument.GetDocumentHistories(id);

            return View(viewModel);
        }

        // POST: Documents/Edit/5

SRS_Game/Views/Documents/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.Document;

@{
    ViewData["Title"] = @Localizer["Add a new document"];
}
<div class="row">
    <div class="col-8">
        <h1>@ViewData["Title"]</h1>
        <h4>@Localizer["Specification of requirements"]</h4>
    </div>
    <div class="col-4 align-bottom text-end">
        <input type="submit" value=@Localizer["Add"] form="create-form" class="btn btn-primary mr-3" />
        @Html.ActionLink(@Localizer["BackToList"].Value, "Index", "Documents", null, new { @class = "btn btn-primary" })
    </div>
</div>
<hr />
@if (ViewBag.Message != null)
{
    <div class="alert alert-@ViewBag.Message.Type" role="alert">
        @ViewBag.Message.Text
    </div>
}
<div class="row">
    <div class="col-sm-6">
        <form id="create-form" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3 row">
                <label asp-for="Name" class="col-sm-3 col-form-label">@Localizer["Name"]</label>
                <div class="col-sm-9">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="ProjectId" class="col-sm-3 col-form-label">@Localizer["Project"]</label>
                <div class="col-sm-9">
                    <select asp-for="ProjectId" class="form-control" asp-items="ViewBag.Projects">
                        <option value="">@Localizer["-- Select an option --"]</option>
                    </select>
                    <span asp-validation-for="ProjectId" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="TeamLeaderId" class="col-sm-3 col-form-label">@Localizer["SupervisorManager"]</label>
                <div class="col-sm-9">
                    <select asp-for="TeamLeaderId" class="form-control" asp-items="ViewBag.Participants">
                        <option value="">@Localizer["-- Select an option --"]</option>
                    </select>
                    <span asp-validation-for="TeamLeaderId" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="Destination" class="col-sm-3 col-form-label">@Localizer["Description"]</label>
                <div class="col-sm-9">
                    <input asp-for="Destination" class="form-control" />
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="AuthorId" class="col-sm-3 col-form-label">@Localizer["Autor"]</label>
                <div class="col-sm-9">
                    <select asp-for="AuthorId" class="form-control" asp-items="ViewBag.Participants">
                        <option value="">@Localizer["-- Select an option --"]</option>
                    </select>
                    <span asp-validation-for="AuthorId" class="text-danger"></span>
                </div>
            </div>
            @*<div class="mb-3 row">
                <label asp-for="UpdateDate" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9"><input asp-for="UpdateDate" class="form-control" /></div>
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="Version" class="col-sm-3 col-form-label"></label>
                <div class="col-sm-9"><input asp-for="Version" class="form-control" /></div>
                <span asp-validation-for="Version" class="text-danger"></span>
            </div> *@
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SRS_Game/Views/Documents/Details.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.DocumentViewModel;

@{
    ViewData["Title"] = @Localizer["Details"];
}
<div class="row">
    <div class="col-8">
        <h1>@Localizer["Document"] @Localizer["Details"]</h1>
        <h4>"@Html.DisplayFor(model => model.Name)"</h4>
    </div>
    <div class="col-4 align-bottom text-end">
        @Html.ActionLink(@Localizer["Edit"].Value, "Edit", "Documents", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink(@Localizer["BackToList"].Value, "Index", "Documents", null, new { @class = "btn btn-primary" })
    </div>
</div>
<hr />
<div class="card">
    <div class="card-header text-center">
        <ul class="nav nav-tabs card-header-tabs" data-bs-tabs="tabs">
            <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="tab" aria-current="true" href="#summary">@Localizer["Summary"]</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#srs-doc">SRS @Localizer["Document"]</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#srs-attachements">@Localizer["Attachements"]</a>
            </li>
        </ul>
    </div>
    <div class="card-body tab-content">
        <div class="tab-pane active" id="summary">
            <div class="row">
                <div class="col-6">
                    <dl class="row">
                        <dt class="col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.Version)]
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Version)
                        </dd>
                        <dt class = "col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.Destination)]
                        </dt>
                        <dd class = "col-sm-8">
                            @Html.DisplayFor(model => model.Destination)
                        </dd>
                        <dt class="col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.Project)]
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Project)
                        </dd>
                        <dt class="col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.Team)]
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Team)
                        </dd>
                        <dt class = "col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.CreatedDate)]
                        </dt>
                        <dd class = "col-sm-8">
                            @Html.DisplayFor(model => model.CreatedDate)
                        </dd>
                        <dt class = "col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.UpdatedDate)]
                        </dt>
                        <dd class = "col-sm-8">
                            @Html.DisplayFor(model => model.UpdatedDate)
                        </dd>
                        <dt class="col-sm-4">
                            @Localizer[Html.DisplayNameFor(model => model.Author)]
                        </dt>
                        <dd class="col-sm-8">
                            @Html.DisplayFor(model => model.Author)
                        </dd>
                    </dl>
                </div>
                <div class="col-6 d-flex align-items-center">
                    <div class="row m-2">
                        <div class="col-2 fw-bold text-white bg-success text-center d-flex align-items-center"><i class="bi bi-emoji-smile"></i>100%</div>
                        <div class="col-3 bg-light fw-bold text-center d-flex align-items-center">Excelent</div>
                        <div class="col-7 bg-dark-subtle">There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. </div>
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col card">
                    <div class="card-header">
                        <h4>@Localizer["Document history"]</h4>
                    </div>
                    <div class="card-body">
                        <partial name="_DocumentHistoryPartial" />
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="srs-doc">
            <pre class="pre-wrap">@Model.XamlContent</pre>
        </div>
        <div class="tab-pane" id="srs-attachements">
            <div class="row mt-4">
                <div class="col card">
                    <div class="card-header">
                        <h4>@Localizer["Attachements"]</h4>
                    </div>
                    <div class="card-body">
                        @if (Model != null && Model.Attachements.Any())
                        {
                            <table class="table table-striped">
                                <tr>
                                    <th>@Localizer["File name"]</th>
                                    <th>@Localizer["Content type"]</th>
                                    <th>@Localizer["CreatedDate"]</th>
                                </tr>
                                @foreach (var attachement in Model.Attachements)
                                {
                                    <tr>
                                        <td>@attachement.FileName</td>
                                        <td>@attachement.ContentType</td>
                                        <td>@attachement.CreatedDate</td>
                                    </tr>
                                }
                            </table>
                        }
                        else
                        {
                            @Localizer["NoAttachements"]
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SRS_Game/Views/Documents/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.Document;

@{
    ViewData["Title"] = Localizer["Edit"];
}
<div class="row">
    <div class="col-8">
        <h1>@Localizer["Document"] - @Localizer["Edit"]</h1>
        <h4>"@Html.DisplayFor(model => model.Name)"</h4>
    </div>
    <div class="col-4 align-bottom text-end">
        <input type="submit" value=@Localizer["Save"] form="srs-header-form" id="srs-submit" class="btn btn-primary mr-3" />
        @Html.ActionLink(@Localizer["Cancel"].Value, "Details", "Documents", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink(@Localizer["BackToList"].Value, "Index", "Documents", null, new { @class = "btn btn-primary" })
    </div>
</div>
<hr />
@if (ViewBag.Message != null)
{
<div class="alert alert-@ViewBag.Message.Type" role="alert">
    @ViewBag.Message.Text
</div>
}
<div class="card">
    <div class="card-header text-center">
        <ul class="nav nav-tabs card-header-tabs" data-bs-tabs="tabs">
            <li class="nav-item">
                <a class="nav-link active" id="srs-header" data-bs-toggle="tab" aria-current="true" href="#summary">@Localizer["Summary"]</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#srs-history">SRS @Localizer["History"]</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="srs-body" data-bs-toggle="tab" href="#srs-doc">SRS @Localizer["Document"]</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-bs-toggle="tab" href="#srs-sources">@Localizer["Source"]</a>
            </li>
        </ul>
    </div>
    <div class="card-body tab-content">
        <div class="tab-pane active" id="summary">
            <div class="row">
                <div class="col-md">
                    <form id="srs-header-form" class="" asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />

                        <table class="table-bordered mb-2 w-100">
                            <tr class="align-top">
                                <td class="form-floating">
                                    <select asp-for="TeamId" class="form-select border-0" asp-items="ViewBag.Teams" onselect="@Model.TeamId"></select>
                                    <label asp-for="TeamId">@Localizer["TeamNumber"]:</label>
                                </td>
                                <td class="form-floating">
                                    <select class="form-select border-0" asp-for="TeamLeaderId" asp-items="ViewBag.Participants" onselect="@Model.TeamLeaderId"></select>
                                    <label asp-for="TeamLeaderId">@Localizer["SupervisorManager"]</label>
                                </td>
                            </tr>
                            <tr>
                                <td class="form-floating" colspan="2">
                                    <select asp-for="ProjectId" class="form-select border-0" asp-items="ViewBag.Projects" onselect="@Model.ProjectId"></select>
                                    <label asp-for="ProjectId">@Localizer["ProjectName"]:</label>
                                </td>
                            </tr>
                        </table>

                        <table class="table-bordered mb-2 w-100">
                            <tr class="align-top">
                                <td class="form-floating pb-0">
                                    <input asp-for="Name" class="form-control-plaintext h4" placeholder="@Localizer["DocumentName"]" />
                                    <label asp-for="Name">@Localizer["DocumentName"]:</label>
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </td>
                                <td class="form-floating pb-0">
                                    <input type="text" class="form-control-plaintext" asp-for="Version" readonly placeholder="@Localizer["VersionNr"]" />
                                    <label asp-for="Version" class="col-sm-3 col-form-label">@Localizer["VersionNr"]:</label>
                                </td>
                            </tr>
                            <tr class="align-top">
                                <td class="form-floating">
                                    <select asp-for="AuthorId" class="form-select border-0" asp-items="ViewBag.Participants" onselect="@Model.AuthorId"></select>
                                    <label asp-for="AuthorId" class="col-sm-3 col-form-label">@Localizer["ResponsibleForTheDocument"]:</label>
                                </td>
                                <td class="form-floating">
                                    <input asp-for="UpdatedDate" asp-format="{0:yyyy-MM-ddTHH:mm}" class="form-control-plaintext" placeholder="@Localizer["UpdatedDate"]" readonly />
                                    <label asp-for="UpdatedDate">@Localizer["UpdatedDate"]:</label>
                                </td>
                            </tr>
                            <tr class="align-top">
                                <td class="form-floating">
                                    <input asp-for="Destination" class="form-control-plaintext" placeholder="@Localizer["Destination"]" />
                                    <label asp-for="Destination">@Localizer["Destination"]:</label>
                                </td>
                                <td class="form-floating">
                                    <input asp-for="CreatedDate" asp-format="{0:yyyy-MM-ddTHH:mm}" class="form-control-plaintext" placeholder="@Localizer["CreatedDate"]" readonly />
                                    <label asp-for="CreatedDate">@Localizer["CreatedDate"]:</label>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="srs-history">
            <div class="row">
                <div class="col card">
                    <div class="card-header">
                        <h4>@Localizer["Document history"]</h4>
                    </div>
                    <div class="card-body">
                        <partial name="_DocumentHistoryPartial" />
                    </div>
                </div>
            </div>
        </div>
        <div class="tab-pane" id="srs-doc">
            <partial name="SrsDocument\_SrsDocEditPartial" />
        </div>
        <div class="tab-pane" id="srs-sources">
            <div class="row">
                <div class="col card">
                    <div class="card-header">
                        <h4>@Localizer["Meeting Transcript"]</h4>
                    </div>
                    <div class="card-body">
                        <h5>@Html.Raw(ViewData["TopicS"])</h5>
                        <p>@Html.Raw(ViewData["MeetingDateS"])</p>
                        <p>@Html.Raw(ViewData["ParticipantsS"])</p>
                        <p>@Html.Raw(ViewData["ContentS"])</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<partial name="SrsDocument\_SrsDocBlankPartial" />

@section Styles {
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/srs-doc.js" asp-append-version="true"></script>
}