SRS_Game/Models/Participant.cs
using Elfie.Serialization;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SRS_Game.Helpers;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;

namespace SRS_Game.Models
{
    public class Participant
    {
        [Key]
        public int Id { get; set; }

        /// <summary>
        /// First name of the participant or company representative
        /// </summary>
        [Required(ErrorMessage = "The field is required")]
        [StringLength(50)]
        [DisplayName("First name")]
        public string FirstName { get; set; }

        /// <summary>
        /// Surname of the participant or company representative
        /// </summary>
        [Required(ErrorMessage = "The field is required")]
        [StringLength(50)]
        [DisplayName("Last name")]
        public string LastName { get; set; }

        /// <summary>
        /// Company name
        /// </summary>
        [StringLength(100)]
        public string? Name { get; set; }

        [EmailAddress]
        [StringLength(50)]
        //[Required(ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "EmailRequired")]
        //[RegularExpression(@"^([0-9a-zA-Z]([\+\-_\.][0-9a-zA-Z]+)*)+@(([0-9a-zA-Z][-\w]*[0-9a-zA-Z]*\.)+[a-zA-Z0-9]{2,3})$", ErrorMessageResourceType = typeof(Resource), ErrorMessageResourceName = "EmailInvalid")]
        public string Email { get; set; }

        [StringLength(15)]
        [DisplayName("Phone number")]
        public string? PhoneNumber { get; set; }

        [StringLength(300)]
        public string? Address { get; set; }

        [Required(ErrorMessage = "The field is required")]
        [DisplayName("External stakholder")]
        public bool IsExternal { get; set; }

        [Required(ErrorMessage = "The field is required")]
        [DisplayName("Created date")]
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        [Required(ErrorMessage = "The field is required")]
        [DisplayName("Updated date")]
        public DateTime UpdatedDate { get; set; } = DateTime.Now;

        // Parameterless constructor required by EF Core
        public Participant() { }

        public Participant(string fname, string lname, string email, string? name, string? phoneNumber, string? address, bool isExternal, DateTime createdDate, DateTime updatedDate)
        {
            FirstName = fname;
            LastName = lname;
            Email = email;
            IsExternal = isExternal;
            Name = name;
            PhoneNumber = phoneNumber;
            Address = address;
            CreatedDate = createdDate;
            UpdatedDate = updatedDate;
        }

        public string GetAddress()
        {
            return MyRegex.NewLineToBr(Address) ?? "";
        }

        public string GetParticipantName()
        {
            return String.Format("{0} {1}", FirstName, LastName);
        }
    }
}

SRS_Game/Controllers/ParticipantsController.cs
using Elfie.Serialization;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.BlazorIdentity.Pages.Manage;
using SRS_Game.Data;
using SRS_Game.Interfaces;
using SRS_Game.Models;
using SRS_Game.Models.Srs;

namespace SRS_Game.Controllers
{
    [Authorize(Policy = "AdminOrOwnerPolicy")]
    public class ParticipantsController : Controller
    {
        private readonly SRS_GameDbContext _context;

        public ParticipantsController(SRS_GameDbContext context)
        {
            _context = context;
        }

        // GET: Participant
        public async Task<IActionResult> Index()
        {
            var participants = await _context.Participants.ToListAsync();
            
            return View(participants);
        }

        // GET: Participant/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants
                .Where(r => r.Id == id)
                .FirstOrDefaultAsync();
            
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // GET: Participant/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Participant/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,FirstName,LastName,Email,PhoneNumber,Address")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                _context.Add(participant);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            return View(participant);
        }

        // GET: Participant/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants.FindAsync(id);
            
            if (participant == null)
            {
                return NotFound();
            }
            return View(participant);
        }

        // POST: Participant/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,FirstName,LastName,Email,PhoneNumber,Address,CreatedDate")] Participant participant)
        {
            if (id != participant.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(participant);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(participant.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(participant);
        }

        // GET: Participant/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var participant = await _context.Participants
                .FirstOrDefaultAsync(m => m.Id == id);
            if (participant == null)
            {
                return NotFound();
            }

            return View(participant);
        }

        // POST: Participant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var participant = await _context.Participants.FindAsync(id);
            if (participant != null)
            {
                _context.Participants.Remove(participant);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Participants.Any(e => e.Id == id);
        }
    }
}

SRS_Game/Views/Participants/Create.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.Participant;

@{
    ViewData["Title"] = @Localizer["Add a new stakholder"];
}
<div class="row">
    <div class="col-8">
        <h1>@ViewData["Title"]</h1>
    </div>
    <div class="col-4 align-bottom text-end">
        <input type="submit" value=@Localizer["Add"] form="create-form" class="btn btn-primary mr-3" />
        @Html.ActionLink(@Localizer["BackToList"].Value, "Index", "Participants", null, new { @class = "btn btn-primary" })
    </div>
</div>
<hr />
@if (ViewBag.Message != null)
{
    <div class="alert alert-@ViewBag.Message.Type" role="alert">
        @ViewBag.Message.Text
    </div>
}
<div class="row">
    <div class="col-sm-6">
        <form id="create-form" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3 row">
                <label asp-for="FirstName" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.FirstName)]</label>
                <div class="col-sm-8">
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="LastName" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.LastName)]</label>
                <div class="col-sm-8">
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="Name" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.Name)]</label>
                <div class="col-sm-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="Email" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.Email)]</label>
                <div class="col-sm-8">
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="PhoneNumber" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.PhoneNumber)]</label>
                <div class="col-sm-8">
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="Address" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.Address)]</label>
                <div class="col-sm-8">
                    <input asp-for="Address" class="form-control" />
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
            </div>
            <div class="mb-3 row">
                <label asp-for="IsExternal" class="col-sm-4 col-form-label">@Localizer[@Html.DisplayNameFor(model => model.IsExternal)]</label>
                <div class="col-sm-8">
                    <input class="form-check-inline mt-2" asp-for="IsExternal" />
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SRS_Game/Views/Participants/Delete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.Participant;

@{
    ViewData["Title"] = @Localizer["Delete"];
}
<div class="row">
    <div class="col-8">
        <h1>@Localizer["Delete"] - "@Model.FirstName @Model.LastName"</h1>
        <h3>@Localizer["Asking"]?</h3>
    </div>
</div>
<hr />
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.Name)]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.FirstName)]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.LastName)]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.PhoneNumber)]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.IsExternal)]
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IsExternal)
        </dd>
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.Address)]
        </dt>
        <dd class="col-sm-10">
            <pre>@Html.DisplayFor(model => model.Address)</pre>
        </dd>
    </dl>
</div>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-primary ms-2">@Localizer["BackToList"]</a>
        </form>
    </div>
</div>

SRS_Game/Views/Participants/Details.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.Participant;

@{
    ViewData["Title"] = Localizer["Details"];
}
<div class="row">
    <div class="col-8">
        <h1>@Localizer["Stakholder"] - @Localizer["Details"]</h1>
    </div>
    <div class="col-4 align-bottom text-end">
        @Html.ActionLink(@Localizer["Edit"].Value, "Edit", "Participants", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink(@Localizer["BackToList"].Value, "Index", "Participants", null, new { @class = "btn btn-primary" })
        @*<a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary mr-3">@Localizer["Edit"]</a>
        <a asp-action="Index" class="btn btn-primary">@Localizer["Back to List"]</a>*@
    </div>
</div>
<hr />
<div class="w-100">
    <dl class="row">
        <dt class = "col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.Name)]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.FirstName)]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.LastName)]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.PhoneNumber)]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.IsExternal)]
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsExternal)
        </dd>
        <dt class="col-sm-2">
            @Localizer[Html.DisplayNameFor(model => model.Address)]
        </dt>
        <dd class="col-sm-10">
            <pre>@Html.DisplayFor(model => model.Address)</pre>
        </dd>
    </dl>
</div>

SRS_Game/Views/Participants/Edit.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model SRS_Game.Models.Participant;

@{
    ViewData["Title"] = Localizer["Edit"];
}
<div class="row">
    <div class="col-8">
        <h1>@Localizer["Stakholder"] - @Localizer["Edit"]</h1>
    </div>
    <div class="col-4 align-bottom text-end">
        <input type="submit" value=@Localizer["Save"] form="edit-form" class="btn btn-primary mr-3" />
        @Html.ActionLink(@Localizer["Cancel"].Value, "Details", "Participants", new { id = Model.Id }, new { @class = "btn btn-primary" })
        @Html.ActionLink(@Localizer["BackToList"].Value, "Index", "Participants", null, new { @class = "btn btn-primary" })
        @*<a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary mr-3">@Localizer["Edit"]</a>
        <a asp-action="Index" class="btn btn-primary">@Localizer["Back to List"]</a>*@
    </div>
</div>
<hr />
@if (ViewBag.Message != null) {
    <div class="alert alert-@ViewBag.Message.Type" role="alert">
        @ViewBag.Message.Text
    </div>
}
<div class="row">
    <div class="col-md-6">
        <form id="edit-form" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CreatedDate" />
            <div class="mb-3 row">
                <label asp-for="Name" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.Name)]</label>
                <div class="col-sm-8"><input asp-for="Name" class="form-control" /></div>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="FirstName" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.FirstName)]</label>
                <div class="col-sm-8"><input asp-for="FirstName" class="form-control" /></div>
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="LastName" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.LastName)]</label>
                <div class="col-sm-8"><input asp-for="LastName" class="form-control" /></div>
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="Email" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.Email)]</label>
                <div class="col-sm-8"><input asp-for="Email" class="form-control" /></div>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="PhoneNumber" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.PhoneNumber)]</label>
                <div class="col-sm-8"><input asp-for="PhoneNumber" class="form-control" /></div>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="IsExternal" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.IsExternal)]</label>
                <div class="col-sm-8 text-center"><input asp-for="IsExternal" class="form-check-input" type="checkbox" /></div>
                <span asp-validation-for="IsExternal" class="text-danger"></span>
            </div>
            <div class="mb-3 row">
                <label asp-for="Address" class="col-sm-4 col-form-label">@Localizer[Html.DisplayNameFor(model => model.Address)]</label>
                <div class="col-sm-8"><textarea asp-for="Address" class="form-control" rows="3"></textarea></div>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SRS_Game/Views/Participants/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@model IEnumerable<SRS_Game.Models.Participant>;

@{
    ViewData["Title"] = Localizer["Stakholders"];
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">@Localizer["Add New Stakholder"]</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Localizer[Html.DisplayNameFor(model => model.Name)]
            </th>
            <th>
                @Localizer[Html.DisplayNameFor(model => model.FirstName)]
            </th>
            <th>
                @Localizer[@Html.DisplayNameFor(model => model.LastName)]
            </th>
            <th class="text-center">
                @Localizer[@Html.DisplayNameFor(model => model.Email)]
            </th>
            <th class="text-center">
                @Localizer[@Html.DisplayNameFor(model => model.PhoneNumber)]
            </th>
            <th class="text-center">
                @Localizer[@Html.DisplayNameFor(model => model.IsExternal)]
            </th>
            <th class="text-center">@Localizer["Actions"]</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
                <td class="text-end">
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.IsExternal)
                </td>
            <td class="text-center">
                <a asp-action="Details" asp-route-id="@item.Id" nt="@item.Id" class="mr-3" title="View"><i class="bi bi-book"></i></a>
                <a asp-action="Edit" asp-route-id="@item.Id" class="mr-3"><i class="bi bi-pen" title="Edit"></i></a>
                <a asp-action="Delete" asp-route-id="@item.Id" nt="@item.Id" class="mr-3" title="Delete"><i class="bi bi-trash"></i></a>
            </td>
        </tr>
    }
    </tbody>
    <tfoot></tfoot>
</table>

@section Styles {
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet" />
    <link href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
}